#!/usr/bin/env bash

if
  [[ -s "/home/yj/.rvm/gems/ruby-2.2.0@global/environment" ]]
then
  source "/home/yj/.rvm/gems/ruby-2.2.0@global/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/yj/.rvm/gems/ruby-2.2.0@global/environment'" >&2
  exit 1
fi
